APT::FTPArchive::Release::Origin "Xrtix OS";
APT::FTPArchive::Release::Label "Xrtix Repository";
APT::FTPArchive::Release::Suite "trixie";
APT::FTPArchive::Release::Codename "trixie";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
